version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: VendaDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  vendas-api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    links:
      - postgres

volumes:
  postgres_data:
